# Generated by Django 5.0.6 on 2024-06-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_ficha_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='sistema',
        ),
        migrations.AddField(
            model_name='ficha',
            name='classe',
            field=models.SmallIntegerField(choices=[(1, 'Conjurador'), (2, 'Invocador'), (3, 'Mago Marcial'), (4, 'Encantador')], default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='doragos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='elemento',
            field=models.SmallIntegerField(choices=[(1, 'Piro'), (2, 'Aero'), (3, 'Geo'), (4, 'Hidro')], default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='equipamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='experiencia',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='feiticos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel',
            field=models.SmallIntegerField(default=1),
        ),
    ]
