# Generated by Django 5.0.6 on 2024-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('durabilidade', models.IntegerField()),
                ('raridade', models.SmallIntegerField(choices=[(1, 'COMUM'), (2, 'INCOMUM'), (3, 'RARO'), (4, 'EPICO'), (5, 'LENDARIO'), (6, 'MITICO'), (7, 'UNICO')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='itens/fotos')),
            ],
        ),
    ]
